- id: '1690595752570'
  alias: Monthly house tasks
  description: ''
  use_blueprint:
    path: mine/add_to_todo_list.yaml
    input:
      time_of_day: 09:00:00
      day_of_month: 1
      items: 'Clean robot vacuum and change bag

        Change Furnace Filter

        Flush whole house water filter

        Run robot vacuum upstairs

        Pay Bills'
      list: todo.home_tasks
      trigger_type: day_of_month_type
      notification_title: Monthly house tasks
- id: '1690595804593'
  alias: Garbage day
  description: ''
  use_blueprint:
    path: mine/add_to_todo_list.yaml
    input:
      time_of_day: '18:00:00'
      day_of_week: 3
      items: Take out trash
      list: todo.home_tasks
      trigger_type: day_of_week_type
      notification_title: Garbage day
- id: '1709602687054'
  alias: Frigate Notification Porch Person
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.porch
      notify_device: c912a4836ddece53925333ce20def0b8
      alert_once: true
      critical: 'true'
      update_thumbnail: true
      zone_filter: true
      zones:
      - on_porch
      labels:
      - person
      - package
      cooldown: 160
      debug: true
      state_filter: false
      update_sub_label: false
      tap_action: /lovelace
      url_1: /lovelace
      button_1: Open app
- id: '1709647869626'
  alias: Frigate Notifications Person in Yard
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.yard
      notify_device: c912a4836ddece53925333ce20def0b8
      alert_once: true
      labels:
      - person
      zone_multi: false
      zone_filter: true
      presence_filter: person.jen
      critical: 'true'
      update_sub_label: false
      zones:
      - entire_yard
      tap_action: /lovelace
      url_1: /lovelace
      button_1: Open app
- id: '1710947464947'
  alias: Clear todo items automatically
  description: ''
  trigger:
  - platform: state
    entity_id:
    - todo.home_tasks
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: todo.remove_completed_items
    metadata: {}
    data: {}
    target:
      entity_id: todo.home_tasks
  mode: single
- id: '1718654431767'
  alias: Frigate notifications Driveway people or cars
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.driveway
      notify_device: c912a4836ddece53925333ce20def0b8
      critical: 'true'
      alert_once: false
      tap_action: /lovelace
      button_1: View Stream
      url_1: /lovelace
      url_2: /ccab4aaf_frigate-fa/dashboard
      button_2: Open Frigate
      zone_filter: true
      zones:
      - entire_driveway
      labels:
      - person
      - car
- id: '1718737007570'
  alias: Jen leaves home
  description: 'Notify if anything is left open/unlocked

    Set thermostat to away

    Set moen flo to away

    Turn off kitchen light'
  trigger:
  - platform: state
    entity_id:
    - person.jen
    attribute: device_trackers
    from: home
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_sm_g986u1
    metadata: {}
    data:
      message: You left!
  - type: turn_off
    device_id: 405d0e9a4a8f359f1386cca76dba82ac
    entity_id: 6156c3435ab014f367e9b277bd830a8a
    domain: switch
  - service: flo.set_away_mode
    metadata: {}
    data: {}
    target:
      device_id: e77ba93b23b9ba7f691f934d80d1df77
  - service: script.notify_if_anything_unlocked_or_open
    metadata: {}
    data: {}
  mode: single
- id: '1718737136374'
  alias: Jen arrives home
  description: 'Set thermostat & moen flo to home

    Turn on kitchen light

    Offer to unlock door or open garage'
  trigger:
  - platform: state
    entity_id:
    - person.jen
    attribute: device_trackers
    to: home
    for:
      hours: 0
      minutes: 0
      seconds: 10
  condition: []
  action:
  - service: notify.mobile_app_sm_g986u1
    metadata: {}
    data:
      message: Welcome home!
  - type: turn_on
    device_id: 405d0e9a4a8f359f1386cca76dba82ac
    entity_id: 6156c3435ab014f367e9b277bd830a8a
    domain: switch
  - service: flo.set_home_mode
    metadata: {}
    data: {}
    target:
      device_id: e77ba93b23b9ba7f691f934d80d1df77
  mode: single
- id: '1718738284559'
  alias: Jen goes to bed
  description: Turn off lights, notify if anything is left open/unlocked
  trigger:
  - platform: state
    entity_id:
    - sensor.sm_g986u1_battery_state
    to: charging
  condition:
  - condition: state
    entity_id: person.jen
    state: home
  - condition: time
    after: '21:00:00'
  action:
  - service: notify.mobile_app_sm_g986u1
    metadata: {}
    data:
      message: Goodnight!
  - type: turn_off
    device_id: 405d0e9a4a8f359f1386cca76dba82ac
    entity_id: 6156c3435ab014f367e9b277bd830a8a
    domain: switch
  - type: turn_off
    device_id: 0d78a45614f73f40073b9b5656761f1a
    entity_id: 8be8dd889bfbad65cd24be899fb43553
    domain: switch
  - service: script.notify_if_anything_unlocked_or_open
    metadata: {}
    data: {}
  mode: single
- id: '1718910142593'
  alias: Set allow automation execution on startup
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.allow_automation_execution
  mode: single
- id: '1718915176839'
  alias: Side door lock jammed notification
  description: ''
  trigger:
  - platform: device
    device_id: 0e5587c11080efee251f5c8a1fb1bea2
    domain: lock
    entity_id: 0a4102f70006900529fd4a53b1081414
    type: jammed
  condition: []
  action:
  - service: notify.mobile_app_sm_g986u1
    metadata: {}
    data:
      message: Side door lock jammed
  mode: single
- id: '1718915278663'
  alias: Side door intrusion became unsafe
  description: ''
  trigger:
  - type: unsafe
    platform: device
    device_id: 0e5587c11080efee251f5c8a1fb1bea2
    entity_id: 3f11db3db94ffa2392be6660b4b9e152
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_sm_g986u1
    metadata: {}
    data:
      message: Side door intrusion became unsafe
  mode: single
- id: '1718915397253'
  alias: Side door lock battery low
  description: ''
  trigger:
  - type: bat_low
    platform: device
    device_id: 0e5587c11080efee251f5c8a1fb1bea2
    entity_id: 96c008d3ae976aec3bc7524c8b876641
    domain: binary_sensor
  - type: bat_low
    platform: device
    device_id: 0e5587c11080efee251f5c8a1fb1bea2
    entity_id: 38e435d4566059402b97766970d0866e
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_sm_g986u1
    metadata: {}
    data:
      message: Replace battery soon on side door lock - battery low!
      title: Side door lock
  - service: notify.persistent_notification
    metadata: {}
    data:
      message: Replace side door lock battery!
  mode: single
- id: '1718915486716'
  alias: Side door lock firmware update available
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 0e5587c11080efee251f5c8a1fb1bea2
    entity_id: 926641b2e8642b77199f5729cc56fc9b
    domain: update
  condition: []
  action:
  - service: notify.persistent_notification
    metadata: {}
    data:
      message: Side door lock firmware update available
  mode: single
