services:
  homeassistant:
    privileged: true
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    volumes:
      - /srv/docker/homeassistant/homeassistant:/config
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    ports:
      - 8123:8123
    network_mode: host
    restart: unless-stopped

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=xxx

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - C:/Projects/docker/mosquitto:/mosquitto
      - C:/Projects/docker/mosquitto/data:/mosquitto/data
      - C:/Projects/docker/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

  zwave:
    container_name: zwave
    image: zwavejs/zwave-js-ui:latest
    restart: unless-stopped
    volumes:
      - /srv/docker/homeassistant/zwave:/usr/src/app/store
    devices:
      - /dev/serial/by-id/usb-xxx:/dev/zwave
    ports:
      - 8091:8091
      - 3000:3000


# set trusted docker internal network
networks:
  default:
    name: homeassistant
    ipam:
      config:
        - subnet: x.x.x.x
          ip_range: x.x.x.x
          gateway: x.x.x.x
