views:
  - title: General
    path: general
    icon: mdi:cog
    cards:
      - type: entities
        entities:
          - input_boolean.currently_fostering
        title: Foster Dog
        show_header_toggle: false
        state_color: true
  - title: Locks
    path: keypad-side_door
    icon: mdi:lock-smart
    panel: false
    badges:
      - input_text.side_door_lockname
      - input_boolean.side_door_lock_notifications
      - input_boolean.side_door_dooraccess_notifications
      - input_boolean.side_door_garageacess_notifications
      - entity: lock.touchscreen_deadbolt
      - entity: input_text.keymaster_side_door_autolock_door_time_day
      - entity: input_text.keymaster_side_door_autolock_door_time_night
      - entity: input_boolean.keymaster_side_door_autolock
      - entity: timer.keymaster_side_door_autolock
    cards:
      - type: vertical-stack
        cards:
          - content: |
              ## Side Door - Code 1
            type: markdown
          - type: entities
            show_header_toggle: false
            entities:
              - entity: input_text.side_door_name_1
              - entity: input_text.side_door_pin_1
              - entity: input_boolean.enabled_side_door_1
              - entity: input_boolean.notify_side_door_1
              - type: divider
              - entity: sensor.connected_side_door_1
                state_color: true
              - entity: binary_sensor.active_side_door_1
                state_color: true
              - type: custom:fold-entity-row
                head:
                  type: section
                  label: Advanced Options
                entities:
                  - entity: input_boolean.reset_codeslot_side_door_1
                  - type: divider
                  - entity: input_boolean.accesslimit_side_door_1
                  - entity: input_number.accesscount_side_door_1
                    type: custom:numberbox-card
                    icon: mdi:key-variant
                    speed: 250
                  - type: divider
                  - entity: input_boolean.daterange_side_door_1
                  - entity: input_datetime.start_date_side_door_1
                  - entity: input_datetime.end_date_side_door_1
                  - type: custom:fold-entity-row
                    head:
                      type: section
                      label: Custom Weekdays
                    entities:
                      - input_boolean.sun_side_door_1
                      - input_boolean.sun_inc_side_door_1
                      - input_datetime.sun_start_date_side_door_1
                      - input_datetime.sun_end_date_side_door_1
                      - type: divider
                      - input_boolean.mon_side_door_1
                      - input_boolean.mon_inc_side_door_1
                      - input_datetime.mon_start_date_side_door_1
                      - input_datetime.mon_end_date_side_door_1
                      - type: divider
                      - input_boolean.tue_side_door_1
                      - input_boolean.tue_inc_side_door_1
                      - input_datetime.tue_start_date_side_door_1
                      - input_datetime.tue_end_date_side_door_1
                      - type: divider
                      - input_boolean.wed_side_door_1
                      - input_boolean.wed_inc_side_door_1
                      - input_datetime.wed_start_date_side_door_1
                      - input_datetime.wed_end_date_side_door_1
                      - type: divider
                      - input_boolean.thu_side_door_1
                      - input_boolean.thu_inc_side_door_1
                      - input_datetime.thu_start_date_side_door_1
                      - input_datetime.thu_end_date_side_door_1
                      - type: divider
                      - input_boolean.fri_side_door_1
                      - input_boolean.fri_inc_side_door_1
                      - input_datetime.fri_start_date_side_door_1
                      - input_datetime.fri_end_date_side_door_1
                      - type: divider
                      - input_boolean.sat_side_door_1
                      - input_boolean.sat_inc_side_door_1
                      - input_datetime.sat_start_date_side_door_1
                      - input_datetime.sat_end_date_side_door_1
      - type: vertical-stack
        cards:
          - content: |
              ## Side Door - Code 2
            type: markdown
          - type: entities
            show_header_toggle: false
            entities:
              - entity: input_text.side_door_name_2
              - entity: input_text.side_door_pin_2
              - entity: input_boolean.enabled_side_door_2
              - entity: input_boolean.notify_side_door_2
              - type: divider
              - entity: sensor.connected_side_door_2
                state_color: true
              - entity: binary_sensor.active_side_door_2
                state_color: true
              - type: custom:fold-entity-row
                head:
                  type: section
                  label: Advanced Options
                entities:
                  - entity: input_boolean.reset_codeslot_side_door_2
                  - type: divider
                  - entity: input_boolean.accesslimit_side_door_2
                  - entity: input_number.accesscount_side_door_2
                    type: custom:numberbox-card
                    icon: mdi:key-variant
                    speed: 250
                  - type: divider
                  - entity: input_boolean.daterange_side_door_2
                  - entity: input_datetime.start_date_side_door_2
                  - entity: input_datetime.end_date_side_door_2
                  - type: custom:fold-entity-row
                    head:
                      type: section
                      label: Custom Weekdays
                    entities:
                      - input_boolean.sun_side_door_2
                      - input_boolean.sun_inc_side_door_2
                      - input_datetime.sun_start_date_side_door_2
                      - input_datetime.sun_end_date_side_door_2
                      - type: divider
                      - input_boolean.mon_side_door_2
                      - input_boolean.mon_inc_side_door_2
                      - input_datetime.mon_start_date_side_door_2
                      - input_datetime.mon_end_date_side_door_2
                      - type: divider
                      - input_boolean.tue_side_door_2
                      - input_boolean.tue_inc_side_door_2
                      - input_datetime.tue_start_date_side_door_2
                      - input_datetime.tue_end_date_side_door_2
                      - type: divider
                      - input_boolean.wed_side_door_2
                      - input_boolean.wed_inc_side_door_2
                      - input_datetime.wed_start_date_side_door_2
                      - input_datetime.wed_end_date_side_door_2
                      - type: divider
                      - input_boolean.thu_side_door_2
                      - input_boolean.thu_inc_side_door_2
                      - input_datetime.thu_start_date_side_door_2
                      - input_datetime.thu_end_date_side_door_2
                      - type: divider
                      - input_boolean.fri_side_door_2
                      - input_boolean.fri_inc_side_door_2
                      - input_datetime.fri_start_date_side_door_2
                      - input_datetime.fri_end_date_side_door_2
                      - type: divider
                      - input_boolean.sat_side_door_2
                      - input_boolean.sat_inc_side_door_2
                      - input_datetime.sat_start_date_side_door_2
                      - input_datetime.sat_end_date_side_door_2
      - type: history-graph
        entities:
          - entity: lock.touchscreen_deadbolt
      - type: logbook
        entities:
          - lock.touchscreen_deadbolt
  - title: Thermostat
    path: thermostat
    icon: mdi:thermometer
    cards:
      - type: thermostat
        entity: climate.thermostat_75_ed_31
        show_current_as_primary: false
        features:
          - type: climate-fan-modes
            style: dropdown
          - type: climate-hvac-modes
      - type: entity
        entity: switch.thermostat_75_ed_31_hold
        state_color: false
      - type: history-graph
        entities:
          - entity: climate.thermostat_75_ed_31
  - icon: mdi:video
    title: Cameras
    path: cameras
    badges:
      - binary_sensor.porch_motion
      - binary_sensor.driveway_motion
      - binary_sensor.yard_motion
    cards:
      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.porch
          - camera_entity: camera.driveway
          - camera_entity: camera.yard
        menu:
          style: overlay
          buttons:
            frigate:
              enabled: false
            substreams:
              enabled: false
        live:
          draggable: false
      - type: custom:swipe-card
        parameters:
          pagination:
            type: bullets
          navigation: null
          keyboard:
            enabled: true
            onlyInViewport: true
        cards:
          - type: picture
            image_entity: image.porch_cat
          - type: picture
            image_entity: image.porch_dog
          - type: picture
            image_entity: image.porch_person
          - type: picture
            image_entity: image.driveway_car
          - type: picture
            image_entity: image.driveway_bicycle
          - type: picture
            image_entity: image.driveway_cat
          - type: picture
            image_entity: image.driveway_dog
          - type: picture
            image_entity: image.driveway_person
          - type: picture
            image_entity: image.yard_person
          - type: picture
            image_entity: image.yard_dog
          - type: picture
            image_entity: image.yard_cat
      - type: entities
        entities:
          - entity: automation.frigate_notification_porch_person
          - entity: automation.driveway_frigate_notification
          - entity: automation.frigate_notifications_person_in_yard
        title: Notifications
        show_header_toggle: false
        state_color: true
  - title: Schedule
    path: schedule
    icon: mdi:calendar-clock
    cards:
      - type: custom:scheduler-card
        include:
          - climate
          - switch
        exclude: []
        sort_by:
          - state
          - relative-time
        display_options:
          primary_info: default
          secondary_info:
            - relative-time
            - days
            - time
            - additional-tasks
          icon: action
