- id: '1737319265419'
  alias: Pre-wake-up
  description: ''
  triggers:
  - trigger: time
    at: 07:45:00
    enabled: false
  - trigger: time
    at:
      entity_id: sensor.jen_s_phone_next_alarm
      offset: -00:15:00
  conditions:
  - condition: template
    value_template: '{{ this.attributes.last_triggered is none or this.attributes.last_triggered
      < today_at() }}

      '
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
      - scene.bedroom_blinds_sunrise_open
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.living_room_blinds_sunrise_open
  mode: single
- id: '1737319582212'
  alias: Sunset
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: '0'
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
      - scene.bedroom_blinds_closed
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
      - scene.living_room_blinds_closed
  mode: single
- id: '1737341124915'
  alias: Laptop unplugged notification
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.jenslaptop_battery_powerline_status
    from: Online
    to: Offline
    for:
      hours: 0
      minutes: 5
      seconds: 0
  conditions: []
  actions:
  - action: notify.mobile_app_jen_s_phone
    metadata: {}
    data:
      message: Laptop Unplugged for 5 minutes
  mode: single
- id: '1737341248636'
  alias: Laptop battery below 50%
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.jenslaptop_battery_charge_remaining_percentage
    above: 0
    below: 49.9
  conditions: []
  actions:
  - action: notify.mobile_app_jen_s_phone
    metadata: {}
    data:
      message: Laptop battery below 50%! Plug it in!!!
  mode: single
- id: '1737775226721'
  alias: Bedtime
  description: Turn off lights
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.jen_s_phone_is_charging
    from: 'off'
    to: 'on'
  conditions:
  - condition: state
    entity_id: sensor.jen_s_phone_charger_type
    state: wireless
  - condition: or
    conditions:
    - condition: time
      after: '21:00:00'
    - condition: time
      before: 04:00:00
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
      - light.entry_overhead
      - light.kitchen_overhead_light
      - light.living_room_lamp
      - light.nightstand_lamp_1
  mode: single
- id: '1737775732350'
  alias: Tap Dial 2 - Toggle entry light
  description: ''
  triggers:
  - device_id: e470ae9c389dda31f6b068030ef64c78
    domain: hue
    type: initial_press
    subtype: 2
    unique_id: e23d286b-545a-4ce9-9f24-92db343d1e09
    trigger: device
  conditions: []
  actions:
  - type: toggle
    device_id: ad790b5e9f17ec010381651f3d8b9dfe
    entity_id: 885440eddba5b40c13b6b1c862ee38a4
    domain: light
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
  - type: turn_off
    device_id: ad790b5e9f17ec010381651f3d8b9dfe
    entity_id: 885440eddba5b40c13b6b1c862ee38a4
    domain: light
  mode: restart
- id: '1737816951391'
  alias: Notify when zwave stick unavailable
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.s2_usb_stick_controller_status
    to: unavailable
    for:
      hours: 0
      minutes: 1
      seconds: 0
  conditions: []
  actions:
  - action: notify.mobile_app_jen_s_phone
    metadata: {}
    data:
      message: Zwave Stick Disconnected
  mode: single
- id: '1737832912929'
  alias: Entry light on when motion detected
  description: ''
  triggers:
  - trigger: state
    entity_id: binary_sensor.entryway_motion
    from: 'off'
    to: 'on'
  conditions:
  - condition: time
    after: 08:00:00
    before: '22:00:00'
  actions:
  - alias: Turn on the light
    action: light.turn_on
    target:
      entity_id:
      - light.entry_overhead
    data: {}
    enabled: true
  - alias: Wait until there is no motion from device
    wait_for_trigger:
      trigger: state
      entity_id: binary_sensor.entryway_motion
      from: 'on'
      to: 'off'
  - alias: Wait the number of seconds that has been set
    delay: 300
  - alias: Turn off the light
    action: light.turn_off
    target:
      entity_id:
      - light.entry_overhead
    data: {}
  mode: restart
  max_exceeded: silent
- id: '1737851384995'
  alias: Dim all lights (dial)
  description: ''
  triggers:
  - device_id: e470ae9c389dda31f6b068030ef64c78
    domain: hue
    type: start
    subtype: counter_clock_wise
    unique_id: 7475398d-567c-4d7e-8919-0b12ea6e8741
    trigger: device
  - device_id: e470ae9c389dda31f6b068030ef64c78
    domain: hue
    type: repeat
    subtype: counter_clock_wise
    unique_id: 7475398d-567c-4d7e-8919-0b12ea6e8741
    trigger: device
  conditions: []
  actions:
  - device_id: c50bbc5e648d4624166c942d3abd2d33
    domain: light
    entity_id: 366d05685fe0c57c65a2fe818dc85e02
    type: brightness_decrease
  - device_id: ad790b5e9f17ec010381651f3d8b9dfe
    domain: light
    entity_id: 885440eddba5b40c13b6b1c862ee38a4
    type: brightness_decrease
    enabled: false
  - device_id: 23d224b52db39d3865e45391653e9dcf
    domain: light
    entity_id: 039e44fae1f4b994badeca43781c907a
    type: brightness_decrease
    enabled: false
  - device_id: f63bbaeafe68c79772e8fce7d3c2c58f
    domain: light
    entity_id: 52d585f2c7eabc853b210dabef87a392
    type: brightness_decrease
    enabled: false
  - variables:
      count: "{% if trigger.event.data.type == 'start' %}\n  5\n{% else %}\n  20\n{%
        endif %}\n"
  mode: single
- id: '1737851449901'
  alias: Brighten all lights (dial)
  description: ''
  triggers:
  - device_id: e470ae9c389dda31f6b068030ef64c78
    domain: hue
    type: start
    subtype: clock_wise
    unique_id: 7475398d-567c-4d7e-8919-0b12ea6e8741
    trigger: device
  - device_id: e470ae9c389dda31f6b068030ef64c78
    domain: hue
    type: repeat
    subtype: clock_wise
    unique_id: 7475398d-567c-4d7e-8919-0b12ea6e8741
    trigger: device
  conditions: []
  actions:
  - device_id: c50bbc5e648d4624166c942d3abd2d33
    domain: light
    entity_id: 366d05685fe0c57c65a2fe818dc85e02
    type: brightness_increase
  - if:
    - condition: device
      type: is_on
      device_id: ad790b5e9f17ec010381651f3d8b9dfe
      entity_id: 885440eddba5b40c13b6b1c862ee38a4
      domain: light
    then:
    - device_id: ad790b5e9f17ec010381651f3d8b9dfe
      domain: light
      entity_id: 885440eddba5b40c13b6b1c862ee38a4
      type: brightness_increase
    alias: Brighten entry light
  - if:
    - condition: device
      type: is_on
      device_id: a9d74f7d43bd1b96cabb55b094d0c199
      entity_id: 461f4dc76d2e5213cf7ba41ff7188fce
      domain: light
    then:
    - device_id: f63bbaeafe68c79772e8fce7d3c2c58f
      domain: light
      entity_id: 52d585f2c7eabc853b210dabef87a392
      type: brightness_increase
    alias: Brighten living room
  - if:
    - condition: device
      type: is_on
      device_id: 55bc5ec883d2c87655662b9df4458abf
      entity_id: e6aea8a170200481d59d1df4467e13dc
      domain: light
    then:
    - device_id: 23d224b52db39d3865e45391653e9dcf
      domain: light
      entity_id: 039e44fae1f4b994badeca43781c907a
      type: brightness_increase
    alias: Brighten bedroom light
  mode: single
- id: '1737930415008'
  alias: Tap Dial dial turn
  description: ''
  triggers:
  - device_id: e470ae9c389dda31f6b068030ef64c78
    domain: hue
    type: start
    subtype: clock_wise
    unique_id: 7475398d-567c-4d7e-8919-0b12ea6e8741
    trigger: device
  - device_id: e470ae9c389dda31f6b068030ef64c78
    domain: hue
    type: repeat
    subtype: clock_wise
    unique_id: 7475398d-567c-4d7e-8919-0b12ea6e8741
    trigger: device
  - device_id: e470ae9c389dda31f6b068030ef64c78
    domain: hue
    type: start
    subtype: counter_clock_wise
    unique_id: 7475398d-567c-4d7e-8919-0b12ea6e8741
    trigger: device
  - device_id: e470ae9c389dda31f6b068030ef64c78
    domain: hue
    type: repeat
    subtype: counter_clock_wise
    unique_id: 7475398d-567c-4d7e-8919-0b12ea6e8741
    trigger: device
  conditions: []
  actions:
  - variables:
      dim_count: "{% if trigger.event.data.type == 'start' and trigger.event.data.subtype
        == 'counter_clock_wise' %}\n  -5\n{% elif trigger.event.data.subtype == 'counter_clock_wise'
        %}\n  -20\n{% elif trigger.event.data.type == 'start' %}\n  5\n{% else %}\n
        \ 20\n{% endif %}\n"
  - action: script.dim_bright_all_lights
    metadata: {}
    data_template:
      brightness_adjustment: '{{ dim_count }}'
  mode: queued
  max: 10
- id: '1738257087909'
  alias: Close bedroom blinds when the sun is gone
  description: ''
  triggers:
  - trigger: time
    at: '12:30:00'
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
      - scene.bedroom_blinds_closed
  mode: single
- id: '1738424753174'
  alias: Tap Dial 1 - Open all blinds fully
  description: ''
  triggers:
  - device_id: e470ae9c389dda31f6b068030ef64c78
    domain: hue
    type: short_release
    subtype: 1
    unique_id: 24f7ec55-bf18-48bc-9ead-24729d43c6df
    trigger: device
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
      - scene.bedroom_blinds_open
      - scene.living_room_blinds_open
  mode: single
- id: '1738424814377'
  alias: Tap Dial Long Press 1 - Open living room/half bedroom
  description: ''
  triggers:
  - device_id: e470ae9c389dda31f6b068030ef64c78
    domain: hue
    type: long_press
    subtype: 1
    unique_id: 24f7ec55-bf18-48bc-9ead-24729d43c6df
    trigger: device
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
      - scene.living_room_blinds_open
      - scene.bedroom_blinds_top_half_open
  mode: single
