- id: '1737319265419'
  alias: Pre-wake-up
  description: ''
  triggers:
  - trigger: time
    at: 07:45:00
    enabled: false
  - trigger: time
    at:
      entity_id: sensor.jen_s_phone_next_alarm
      offset: -00:15:00
  conditions:
  - condition: template
    value_template: '{{ this.attributes.last_triggered is none or this.attributes.last_triggered
      < today_at() }}

      '
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
      - scene.bedroom_blinds_sunrise_open
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.living_room_blinds_sunrise_open
  mode: single
- id: '1737319582212'
  alias: Sunset
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: '0'
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
      - scene.bedroom_blinds_closed
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
      - scene.living_room_blinds_closed
  mode: single
- id: '1737775226721'
  alias: Bedtime
  description: Turn off lights
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.jen_s_phone_is_charging
    from: 'off'
    to: 'on'
  conditions:
  - condition: state
    entity_id: sensor.jen_s_phone_charger_type
    state: wireless
  - condition: or
    conditions:
    - condition: time
      after: '21:00:00'
    - condition: time
      before: 04:00:00
  actions:
  - action: script.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: script.turn_off_all_lights
  mode: single
- id: '1737816951391'
  alias: Notify when zwave stick unavailable
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.s2_usb_stick_controller_status
    to: unavailable
    for:
      hours: 0
      minutes: 1
      seconds: 0
  conditions: []
  actions:
  - action: notify.mobile_app_sm_g986u1
    metadata: {}
    data:
      message: Zwave Stick Disconnected
  mode: single
- id: '1737832912929'
  alias: Entry light on when motion detected
  description: ''
  triggers:
  - trigger: state
    entity_id: binary_sensor.entryway_motion
    from: 'off'
    to: 'on'
  conditions:
  - condition: time
    after: 08:00:00
    before: '22:00:00'
  actions:
  - alias: Turn on the light
    action: light.turn_on
    target:
      entity_id:
      - light.entry_overhead
    data: {}
    enabled: true
  - alias: Wait until there is no motion from device
    wait_for_trigger:
      trigger: state
      entity_id: binary_sensor.entryway_motion
      from: 'on'
      to: 'off'
  - alias: Wait the number of seconds that has been set
    delay: 300
  - alias: Turn off the light
    action: light.turn_off
    target:
      entity_id:
      - light.entry_overhead
    data: {}
  mode: restart
  max_exceeded: silent
- id: '1738257087909'
  alias: Close bedroom blinds when the sun is gone
  description: ''
  triggers:
  - trigger: time
    at: '12:30:00'
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
      - scene.bedroom_blinds_closed
  mode: single
- id: '1742762227573'
  alias: Add monthly tasks to todo list
  description: ''
  use_blueprint:
    path: mine/add_to_todo_list.yaml
    input:
      time_of_day: 08:00:00
      trigger_type: day_of_month_type
      day_of_month: 1
      items: 'Pay Bills

        Empty robot vacuum

        Clean air filter

        Clean humidifier

        Clean washing machine filter

        Check blinds charge

        Clean heater filters'
      list: todo.to_do
- id: '1710947464947'
  alias: Clear todo items automatically
  description: ''
  triggers:
  - entity_id:
    - todo.to_do
    trigger: state
  conditions: []
  actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - metadata: {}
    data: {}
    target:
      entity_id:
      - todo.to_do
    action: todo.remove_completed_items
  mode: single
- id: '1743278154096'
  alias: Bedtime - away
  description: ''
  triggers:
  - trigger: time
    at: '23:00:00'
  conditions:
  - condition: state
    entity_id: person.jen
    state: not_home
  actions:
  - action: script.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: script.turn_off_all_lights
  mode: single
