blueprint:
  name: Add to Shopping List
  description: Add items to the shopping_list integration on a schedule
  domain: automation
  author: Jen Gettings
  input:
    time_of_day: 
      name: Time of day
      description: When to run the automation
      selector: 
        time:
      default: 07:00:00
    day_of_month:
      name: Day of Month
      description: Which day the item should be added to the List. Optional - if omitted it will run daily
      selector:
        number:
          min: 1
          max: 31
      default: {}
    day_of_week:
      name: Day of Week
      description: Which day the item should be added to the list. 0 is Monday and 6 is Sunday. Optional - if omitted it will run daily
      selector: 
        number:
          min: 0
          max: 6
      default: {}
    items:
      name: Items to add, use a new line for each
      selector: 
        text:
          multiline: true
      default: Enter text to add to the list
trigger:
- platform: time
  at: !input time_of_day
variables:
  day_of_month: !input day_of_month
  day_of_week: !input day_of_week
  itemsList: !input items
condition:
- condition: template
  value_template: '{{ day_of_month|length == 0 or now().day == day_of_month }}'
- condition: template
  value_template: '{{ day_of_week|length == 0 or now().weekday == day_of_week }}'
action:
  repeat:
    for_each: '{{ itemsList.split("\n") }}'
    sequence:
      - service: shopping_list.add_item
        data:
          name: "{{ repeat.item }}"
mode: single

# TODO add notification